# Generated by Django 3.1 on 2020-11-12 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_safe_deposit', models.BooleanField()),
                ('guest_feedback', models.BooleanField()),
                ('future_reservation', models.BooleanField()),
                ('luggage_assistance', models.BooleanField()),
                ('transport_option', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutDialogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_minibar_charge', models.BooleanField()),
                ('post_minibar_charge_correctly', models.BooleanField()),
                ('present', models.BooleanField()),
                ('get_signature', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_payment_mode', models.BooleanField()),
                ('signature_after_pay', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_stay_detail', models.BooleanField()),
                ('collect_key_card', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_information', models.IntegerField()),
                ('present_folio', models.IntegerField()),
                ('process_payment', models.IntegerField()),
                ('assistance_obtain', models.IntegerField()),
                ('assistance_obtain_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.ao')),
                ('present_folio_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.pf')),
                ('process_payment_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.pp')),
                ('stay_information_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.si')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('author_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkouttask')),
            ],
        ),
    ]
