# Generated by Django 3.1 on 2020-11-12 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinDialogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_payment_mode', models.BooleanField()),
                ('deposit_amount', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key_card_level', models.BooleanField()),
                ('issue_key_card_room_number', models.BooleanField()),
                ('explain_keycard', models.BooleanField()),
                ('advise_breakfast', models.BooleanField()),
                ('advise_internet', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='L',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luggage_assistance', models.BooleanField()),
                ('close_with_pleasantries_anything', models.BooleanField()),
                ('close_with_pleasantries_pleasant', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_passport', models.BooleanField()),
                ('locate_reservation', models.BooleanField()),
                ('update_registration_card', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.BooleanField()),
                ('departure_date', models.BooleanField()),
                ('room_type', models.BooleanField()),
                ('room_rate', models.BooleanField()),
                ('departure_time', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckinTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.IntegerField()),
                ('registration_card_verify', models.IntegerField()),
                ('registration_card_accurately', models.IntegerField()),
                ('stay_details_confirmation', models.IntegerField()),
                ('deposit_collected_correctly', models.IntegerField()),
                ('signature', models.IntegerField()),
                ('room_checked_smoking', models.IntegerField()),
                ('guidelines', models.IntegerField()),
                ('luggage', models.IntegerField()),
                ('deposit_collected_correctly_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.dcc')),
                ('guidelines_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.g')),
                ('luggage_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.l')),
                ('registration_card_verify_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.rcv')),
                ('stay_details_confirmation_subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.sdc')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('total_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('author_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkin.checkintask')),
            ],
        ),
    ]
